DECLARE  @DATABASE_NAME VARCHAR(256) = 'MASTER'
DECLARE @LOCATION VARCHAR(256)='\\NAV-C00DB04P-B\Share'
DECLARE @QUERY VARCHAR(MAX)
DECLARE @BACKUPTYPE VARCHAR(10)
DECLARE @NUMBEROFFILES VARCHAR(10)
DECLARE @DATE VARCHAR(10)=REPLACE(CONVERT(VARCHAR(10), GETDATE(), 110),'-','_')
------------- Create folder to backup as per date

SET @QUERY = 'EXEC master.dbo.xp_cmdshell ''' + 'mkDir "' + @LOCATION  +'\'+ @DATE + '"'''


PRINT @QUERY

EXEC (@QUERY)

SET @QUERY =  'BACKUP DATABASE NAIS_Volvo_Prod TO DISK = '''+@LOCATION+'\'+@DATE+'\'+@DATABASE_NAME+'.BAK'''; 

PRINT @QUERY

EXEC (@QUERY)