	--SET NOCOUNT ON
	BEGIN
	DECLARE @PATH NVARCHAR(100),@FILEFORMAT NVARCHAR(100),@DATE DATETIME
	SET @FILEFORMAT=CONVERT(varchar(8), DATEADD(day, -1, convert(date, GETDATE())), 112) 
	SET @PATH='\\NAV-C00DB04P-B\Share\LOG'
	SET @DATE='2016-02-05 14:16:49.433'
	--EXEC XP_CMDSHELL 'DEL '+FILENAME
-------------------------------------//	GET FILE NAMES	//---------------------------------------
	DECLARE @FNAME TABLE (ID INT IDENTITY(1,1),FNAME NVARCHAR(400),DEPTH INT,FILES INT)
	DECLARE @QUERY NVARCHAR(100)
	SET @QUERY='EXEC XP_DIRTREE '''+@PATH+''',10,1'
	INSERT INTO @FNAME EXEC (@QUERY)


--//		GET CREATION DATE				--//

	DECLARE @FDETAIL TABLE(ID INT IDENTITY(1,1),NAME NVARCHAR(100))

	set @QUERY = 'EXEC XP_CMDSHELL ''DIR /T:C "'+@PATH+'", 10, 1'''
	print @QUERY
	INSERT INTO @FDETAIL EXEC (@QUERY)
	begin try
	DROP TABLE #FDETAILS 
	end try
	begin catch
	print ''
	end catch
	SELECT * INTO #FDETAILS FROM @FDETAIL

---------------------------------//	GET TABULAR DETAILS //----------------------------------------
	
	DECLARE @FILEDETAILS TABLE(ID INT IDENTITY(1,1),FNAME NVARCHAR(100),CREATION_DATE NVARCHAR(100))
	DECLARE @FCOUNT INT
	SET @FCOUNT=(SELECT COUNT(*) FROM @FNAME)
	DECLARE @FILENAME NVARCHAR(100)
	

	WHILE @FCOUNT>0
	BEGIN
	SET @FILENAME=(SELECT FNAME FROM @FNAME WHERE ID=@FCOUNT)
	SET @QUERY='SELECT NAME FROM #FDETAILS WHERE NAME LIKE (''%'+@FILENAME+'%'')'
	INSERT INTO @FILEDETAILS (FNAME) EXEC(@QUERY)
	SET @FCOUNT=@FCOUNT-1
	END
	
	
	SET @FCOUNT =(SELECT COUNT(*) FROM @FILEDETAILS)
	DECLARE @TESTNAME TABLE (ID INT IDENTITY(1,1),NAMES NVARCHAR(400))
	WHILE @FCOUNT>0
	BEGIN
	SET @FILENAME=(SELECT FNAME FROM @FILEDETAILS WHERE ID=@FCOUNT)
	DECLARE @T NVARCHAR(100)
	SET @T=@FILENAME
	SET @T=@T+' '
	;WITH MYCTE(START,[END])AS(
	SELECT 1 AS START,CHARINDEX(' ',@T,1) AS [END]
	UNION ALL
	SELECT [END]+1 AS START,CHARINDEX(' ',@T,([END]+1)) AS [END] FROM MYCTE WHERE [END]<LEN(@T))
	INSERT INTO @TESTNAME
	SELECT SUBSTRING(@T,START,[END]-START) FROM MYCTE
	SET @FCOUNT=@FCOUNT-1
	END
	DELETE FROM @TESTNAME WHERE NAMES IN (' ','0')

	DECLARE @TESTNAMES TABLE (ID INT IDENTITY(1,1),NAMES NVARCHAR(400))
	INSERT INTO @TESTNAMES SELECT NAMES FROM @TESTNAME 	

	DECLARE @F_NAME NVARCHAR(400),@CREATION_DATE NVARCHAR(100)
	SET @FCOUNT=(SELECT COUNT(*) FROM @TESTNAMES)	
	DELETE FROM @FILEDETAILS
	WHILE @FCOUNT>0
	BEGIN
	SET @CREATION_DATE=(SELECT NAMES FROM @TESTNAMES WHERE ID=@FCOUNT-3)+' '+
						(SELECT NAMES FROM @TESTNAMES WHERE ID=(@FCOUNT-2))+' '+
						(SELECT NAMES FROM @TESTNAMES WHERE ID=@FCOUNT-1) 
	SET @F_NAME=(SELECT NAMES FROM @TESTNAMES WHERE ID=@FCOUNT)
	INSERT INTO @FILEDETAILS (FNAME,CREATION_DATE) VALUES (@F_NAME,@CREATION_DATE)
	SET @FCOUNT=@FCOUNT-4
	END
	DROP TABLE #FILEDETAILS
	SELECT * INTO #FILEDETAILS FROM @FILEDETAILS 



	DECLARE @DELETENAMES TABLE(ID INT IDENTITY(1,1),FNAME NVARCHAR(100))
	SET @QUERY='SELECT FNAME FROM #FILEDETAILS WHERE FNAME LIKE (''%'+@FILEFORMAT+'%'')'
	INSERT INTO @DELETENAMES (FNAME) EXEC (@QUERY)
	
	
	DECLARE @DEL NVARCHAR(800)
	SET @FCOUNT=(SELECT COUNT(*) FROM @DELETENAMES)+1
	WHILE @FCOUNT>0 
	BEGIN

	SET @QUERY=(SELECT FNAME FROM @DELETENAMES WHERE ID=@FCOUNT)
	SET @DEL='Del "'+@path+'\'+@QUERY++'"'
	EXEC XP_CMDSHELL @DEL	
	PRINT @DEL
	
	SET @FCOUNT=@FCOUNT-1
	END
--------------------------------//DELETE FILE//-------------------------------------------------


----------------------------------// EOF //-------------------------------------------------------
	END