CREATE  PROCEDURE IX_CXN( @QUERY VARCHAR(MAX))
AS 
BEGIN
SET NOCOUNT ON;

DECLARE @TABLENAME TABLE(TABLE_NAME VARCHAR(MAX),ALIAS VARCHAR(MAX))
DECLARE @COLUMNS_JOIN TABLE(COL VARCHAR(MAX),COLUMN_NAME VARCHAR(MAX),ALIAS VARCHAR(MAX))
DECLARE @NAME VARCHAR(MAX),@ALIAS VARCHAR(MAX),@J_QUERY VARCHAR(MAX),@W_QUERY VARCHAR(MAX)
DECLARE @WHERE_JOIN TABLE(COL VARCHAR(MAX),COLUMN_NAME VARCHAR(MAX),ALIAS VARCHAR(MAX))

----------------------//FROM//------------
SET @QUERY= LTRIM(substring(@QUERY,charindex('FROM ',@query COLLATE SQL_Latin1_General_CP1_CS_AS)+4,len(@query)))
SET @NAME=LTRIM(left(@QUERY,CHARINDEX(' ',@QUERY)))
SET @QUERY= LTRIM(substring(@QUERY,CHARINDEX(@NAME,@QUERY)+len(@NAME),len(@query)))
SET @ALIAS=LTRIM(left(@QUERY,CHARINDEX(' ',@QUERY)))
SET @QUERY= LTRIM(substring(@QUERY,CHARINDEX(@ALIAS,@QUERY)+len(@ALIAS),len(@query)))
INSERT INTO @TABLENAME VALUES (@NAME,@ALIAS)

UPDATE @TABLENAME SET TABLE_NAME=LTRIM(RTRIM(TABLE_NAME))
UPDATE @TABLENAME SET ALIAS=LTRIM(RTRIM(ALIAS))

----------------------//JOIN//------------
SET @J_QUERY=@QUERY

WHILE(CHARINDEX('JOIN ',@QUERY COLLATE SQL_Latin1_General_CP1_CS_AS))>0
BEGIN
SET @QUERY= LTRIM(substring(@QUERY,charindex('JOIN ',@query COLLATE SQL_Latin1_General_CP1_CS_AS)+5,len(@query)))
SET @NAME=LTRIM(left(@QUERY,CHARINDEX(' ',@QUERY)))
SET @QUERY= LTRIM(substring(@QUERY,CHARINDEX(@NAME,@QUERY)+len(@NAME),len(@query)))
SET @ALIAS=LTRIM(left(@QUERY,CHARINDEX(' ',@QUERY)))
SET @QUERY= LTRIM(substring(@QUERY,CHARINDEX(@ALIAS,@QUERY)+len(@ALIAS),len(@query)))
INSERT INTO @TABLENAME VALUES (LTRIM(RTRIM(@NAME)),LTRIM(RTRIM(@ALIAS)))
END

UPDATE @TABLENAME SET TABLE_NAME=LTRIM(RTRIM(TABLE_NAME))
UPDATE @TABLENAME SET ALIAS=LTRIM(RTRIM(ALIAS))

---------------------------------------// JOIN //----------------------------------------------

IF (CHARINDEX('WHERE',@J_QUERY)<>0)
SET @J_QUERY=SUBSTRING(@J_QUERY,0,CHARINDEX('WHERE ',@J_QUERY COLLATE SQL_Latin1_General_CP1_CS_AS))
ELSE
SET @J_QUERY=SUBSTRING(@J_QUERY,0,LEN(@J_QUERY))


DECLARE  @strngLen int
DECLARE @split TABLE(siteId VARCHAR(100))
WHILE CHARINDEX(' ', @J_QUERY) > 0
BEGIN
    SET @strngLen = CHARINDEX(' ', @J_QUERY);

    INSERT INTO @split
    SELECT SUBSTRING(@J_QUERY,1,@strngLen - 1);

    SET @J_QUERY = SUBSTRING(@J_QUERY, @strngLen + 1, LEN(@J_QUERY));
END

INSERT INTO @split
SELECT @J_QUERY

INSERT INTO @COLUMNS_JOIN
SELECT SITEID,SUBSTRING(SITEID,0,CHARINDEX('.',SITEID)),REPLACE(SITEID,SUBSTRING(SITEID,0,CHARINDEX('.',SITEID))+'.','') FROM @SPLIT WHERE SITEID  LIKE '%.%'

---------------------------------------// WHERE //----------------------------------------------

SET @W_QUERY=SUBSTRING(@QUERY,CHARINDEX('WHERE ',@QUERY COLLATE SQL_Latin1_General_CP1_CS_AS),LEN(@QUERY))

WHILE CHARINDEX(' ', @W_QUERY) > 0
BEGIN
    SET @strngLen = CHARINDEX(' ', @W_QUERY);
    INSERT INTO @split
    SELECT SUBSTRING(@W_QUERY,1,@strngLen - 1);

    SET @W_QUERY = SUBSTRING(@W_QUERY, @strngLen + 1, LEN(@W_QUERY));
END

INSERT INTO @split
SELECT @W_QUERY

INSERT INTO @WHERE_JOIN
SELECT SITEID,SUBSTRING(SITEID,0,CHARINDEX('.',SITEID)),REPLACE(SITEID,SUBSTRING(SITEID,0,CHARINDEX('.',SITEID))+'.','') FROM @SPLIT WHERE SITEID  LIKE '%.%'

-----------------------------------------------------// RESULT //----------------------

UPDATE @WHERE_JOIN SET COL=LTRIM(RTRIM(COL)),COLUMN_NAME=LTRIM(RTRIM(COLUMN_NAME)),ALIAS=LTRIM(RTRIM(ALIAS))
UPDATE @COLUMNS_JOIN SET COL=LTRIM(RTRIM(COL)),COLUMN_NAME=LTRIM(RTRIM(COLUMN_NAME)),ALIAS=LTRIM(RTRIM(ALIAS))

INSERT INTO @COLUMNS_JOIN
SELECT
	DISTINCT
	   m.COL 
     , m.COLUMN_NAME
     , ALIAS = STUFF((
          SELECT DISTINCT ',' + md.ALIAS
          FROM @WHERE_JOIN md
          WHERE m.COLUMN_NAME = md.COLUMN_NAME
          FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '')
FROM @WHERE_JOIN m

SELECT DISTINCT 
	'CREATE INDEX IX_'+T.TABLE_NAME+'__'+REPLACE(C.ALIAS,',','_')+' ON '+TABLE_NAME+' ('+C.ALIAS+');'
 FROM @COLUMNS_JOIN C
INNER JOIN  @TABLENAME T  ON (T.ALIAS=C.COLUMN_NAME)

END