DECLARE @SPID VARCHAR(MAX),@QUERY VARCHAR(MAX),@COUNT INT

SET @SPID='52'

DECLARE @SP_WHO2 TABLE (ID INT IDENTITY(1,1),SPID VARCHAR(MAX),Status	 VARCHAR(MAX),Login	 VARCHAR(MAX),HostName	 VARCHAR(MAX),BlkBy VARCHAR(MAX),DBName VARCHAR(MAX),	Command VARCHAR(MAX),	CPUTime VARCHAR(MAX),	DiskIO VARCHAR(MAX),	LastBatch VARCHAR(MAX),	ProgramName VARCHAR(MAX),		SPD VARCHAR(MAX),	REQUESTID VARCHAR(MAX))

DECLARE @INPUT_BUFFER TABLE (ID INT IDENTITY(1,1),SPID VARCHAR(MAX),EventType	 VARCHAR(MAX),Parameters	 VARCHAR(MAX),EventInfo VARCHAR(MAX))

SET @QUERY='SP_WHO2 '+@SPID

INSERT INTO @SP_WHO2 EXEC (@QUERY)

SET @QUERY='DBCC INPUTBUFFER('+@SPID+');'

INSERT INTO @INPUT_BUFFER(EventType,Parameters,EventInfo) EXEC (@QUERY)
UPDATE @INPUT_BUFFER SET SPID=@SPID WHERE SPID IS NULL


IF (SELECT TOP 1 BLKBY FROM @SP_WHO2 WHERE BlkBy<>'  .' ORDER BY ID DESC) IS NOT NULL
BEGIN
set @count=5

WHILE (@COUNT>0)
BEGIN
SET @SPID=(SELECT TOP 1 BLKBY FROM @SP_WHO2 WHERE BlkBy<>'  .' ORDER BY ID DESC)

SET @QUERY='SP_WHO2 '+@SPID

INSERT INTO @SP_WHO2 EXEC (@QUERY)

SET @QUERY='DBCC INPUTBUFFER('+@SPID+');'
INSERT INTO @INPUT_BUFFER(EventType,Parameters,EventInfo) EXEC (@QUERY)
UPDATE @INPUT_BUFFER SET SPID=@SPID WHERE SPID IS NULL

SET @COUNT=@COUNT-1
END 

END



SELECT DISTINCT S.SPID,LOGIN,BlkBy,DBName,COMMAND,I.EventInfo FROM @SP_WHO2 S
INNER JOIN @INPUT_BUFFER I ON I.SPID=S.SPID







