DELIMITER $$

DROP PROCEDURE IF EXISTS proc_loop_test $$
CREATE PROCEDURE proc_loop_test()
BEGIN

DECLARE done INT DEFAULT FALSE;
DECLARE i INTEGER;
DECLARE n INTEGER;
DECLARE val INTEGER;
DECLARE curs1 CURSOR FOR SELECT card_id,status_id FROM maximum_status;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

OPEN curs1;
read_loop: LOOP

FETCH curs1 INTO i,n;
IF done THEN LEAVE read_loop;
END IF;

SET val=n;
WHILE (val>0) DO
INSERT INTO TOTAL_CARD_STATUS SELECT i,val;
SET val=val-1;
END WHILE;

END LOOP;

CLOSE curs1;
END$$
DELIMITER ; 